"""Add review-tracking fields to Error

Revision ID: 08e1c1f201a9
Revises: 
Create Date: 2025-06-15 14:40:22.110949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e1c1f201a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('error', sa.Column('last_reviewed', sa.DateTime(), nullable=True))
    op.add_column('error', sa.Column('last_reviewed_correctly', sa.DateTime(), nullable=True))
    op.add_column('error', sa.Column('review_count', sa.Integer(), nullable=True))
    op.add_column('error', sa.Column('correct_review_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('error', 'correct_review_count')
    op.drop_column('error', 'review_count')
    op.drop_column('error', 'last_reviewed_correctly')
    op.drop_column('error', 'last_reviewed')
    # ### end Alembic commands ###
